### ISSUE TITLE
Issue for Rails 4.2

### ISSUE THREAD

**Issue by mostafa-zahran** [fortesinformatica/jasper-rails#42]
I found this error when installing the gem on rails 4 but it works fine on rails 3

bin/rake Error:[rake --tasks] /home/mostafa/.rvm/gems/ruby-2.2.1@global/gems/activesupport-4.2.1.rc4/lib/active_support/dependencies.rb:274:in 'require': cannot load such file -- action_controller/metal/responder (LoadError) from /home/mostafa/.rvm/gems/ruby-2.2.1@global/gems/activesupport-4.2.1.rc4/lib/active_support/dependencies.rb:274:in 'block in require' from /home/mostafa/.rvm/gems/ruby-2.2.1@global/gems/activesupport-4.2.1.rc4/lib/active_support/dependencies.rb:240:in 'load_dependency' from /home/mostafa/.rvm/gems/ruby-2.2.1@global/gems/activesupport-4.2.1.rc4/lib/active_support/dependencies.rb:274:in 'require' from /home/mostafa/.rvm/gems/ruby-2.2.1@global/gems/jasper-rails-1.0.3/lib/jasper-rails.rb:26:in '<top (required)>' from /home/mostafa/.rvm/gems/ruby-2.2.1@global/gems/bundler-1.9.4/lib/bundler/runtime.rb:76:in 'require' from /home/mostafa/.rvm/gems/ruby-2.2.1@global/gems/bundler-1.9.4/lib/bundler/runtime.rb:76:in 'block (2 levels) in require' from /home/mostafa/.rvm/gems/ruby-2.2.1@global/gems/bundler-1.9.4/lib/bundler/runtime.rb:72:in 'each' from /home/mostafa/.rvm/gems/ruby-2.2.1@global/gems/bundler-1.9.4/lib/bundler/runtime.rb:72:in 'block in require' from /home/mostafa/.rvm/gems/ruby-2.2.1@global/gems/bundler-1.9.4/lib/bundler/runtime.rb:61:in 'each' from /home/mostafa/.rvm/gems/ruby-2.2.1@global/gems/bundler-1.9.4/lib/bundler/runtime.rb:61:in 'require' from /home/mostafa/.rvm/gems/ruby-2.2.1@global/gems/bundler-1.9.4/lib/bundler.rb:134:in 'require' from /config/application.rb:30:in '<top (required)>' from /home/mostafa/.rvm/gems/ruby-2.2.1@global/gems/spring-1.7.2/lib/spring/application.rb:82:in 'require' from /home/mostafa/.rvm/gems/ruby-2.2.1@global/gems/spring-1.7.2/lib/spring/application.rb:82:in 'preload' from /home/mostafa/.rvm/gems/ruby-2.2.1@global/gems/spring-1.7.2/lib/spring/application.rb:143:in 'serve' from /home/mostafa/.rvm/gems/ruby-2.2.1@global/gems/spring-1.7.2/lib/spring/application.rb:131:in 'block in run' from /home/mostafa/.rvm/gems/ruby-2.2.1@global/gems/spring-1.7.2/lib/spring/application.rb:125:in 'loop' from /home/mostafa/.rvm/gems/ruby-2.2.1@global/gems/spring-1.7.2/lib/spring/application.rb:125:in 'run' from /home/mostafa/.rvm/gems/ruby-2.2.1@global/gems/spring-1.7.2/lib/spring/application/boot.rb:19:in '<top (required)>' from /home/mostafa/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in 'require' from /home/mostafa/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in 'require' from -e:1:in '<main>' Error:[rake --prereqs] /home/mostafa/.rvm/gems/ruby-2.2.1@global/gems/activesupport-4.2.1.rc4/lib/active_support/dependencies.rb:274:in 'require': cannot load such file -- action_controller/metal/responder (LoadError) from /home/mostafa/.rvm/gems/ruby-2.2.1@global/gems/activesupport-4.2.1.rc4/lib/active_support/dependencies.rb:274:in 'block in require' from /home/mostafa/.rvm/gems/ruby-2.2.1@global/gems/activesupport-4.2.1.rc4/lib/active_support/dependencies.rb:240:in 'load_dependency' from /home/mostafa/.rvm/gems/ruby-2.2.1@global/gems/activesupport-4.2.1.rc4/lib/active_support/dependencies.rb:274:in 'require' from /home/mostafa/.rvm/gems/ruby-2.2.1@global/gems/jasper-rails-1.0.3/lib/jasper-rails.rb:26:in '<top (required)>' from /home/mostafa/.rvm/gems/ruby-2.2.1@global/gems/bundler-1.9.4/lib/bundler/runtime.rb:76:in 'require' from /home/mostafa/.rvm/gems/ruby-2.2.1@global/gems/bundler-1.9.4/lib/bundler/runtime.rb:76:in 'block (2 levels) in require' from /home/mostafa/.rvm/gems/ruby-2.2.1@global/gems/bundler-1.9.4/lib/bundler/runtime.rb:72:in 'each' from /home/mostafa/.rvm/gems/ruby-2.2.1@global/gems/bundler-1.9.4/lib/bundler/runtime.rb:72:in 'block in require' from /home/mostafa/.rvm/gems/ruby-2.2.1@global/gems/bundler-1.9.4/lib/bundler/runtime.rb:61:in 'each' from /home/mostafa/.rvm/gems/ruby-2.2.1@global/gems/bundler-1.9.4/lib/bundler/runtime.rb:61:in 'require' from /home/mostafa/.rvm/gems/ruby-2.2.1@global/gems/bundler-1.9.4/lib/bundler.rb:134:in 'require' from config/application.rb:30:in '<top (required)>' from /home/mostafa/.rvm/gems/ruby-2.2.1@global/gems/spring-1.7.2/lib/spring/application.rb:82:in 'require' from /home/mostafa/.rvm/gems/ruby-2.2.1@global/gems/spring-1.7.2/lib/spring/application.rb:82:in 'preload' from /home/mostafa/.rvm/gems/ruby-2.2.1@global/gems/spring-1.7.2/lib/spring/application.rb:143:in 'serve' from /home/mostafa/.rvm/gems/ruby-2.2.1@global/gems/spring-1.7.2/lib/spring/application.rb:131:in 'block in run' from /home/mostafa/.rvm/gems/ruby-2.2.1@global/gems/spring-1.7.2/lib/spring/application.rb:125:in 'loop' from /home/mostafa/.rvm/gems/ruby-2.2.1@global/gems/spring-1.7.2/lib/spring/application.rb:125:in 'run' from /home/mostafa/.rvm/gems/ruby-2.2.1@global/gems/spring-1.7.2/lib/spring/application/boot.rb:19:in '<top (required)>' from /home/mostafa/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in 'require' from /home/mostafa/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in 'require' from -e:1:in '<main>'

**Comment by tega90** [comment]
I'm getting the same error. Is this planned to be fixed any time soon?

**Comment by dsadaka** [comment]
No plans to upgrade this gem for Rails 5?
